name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '6.0.x'

    - name: Build and Publish
      run: |
        cd src/DedicatedServerTool.Avalonia
        dotnet publish -r win-x64 -c Release --self-contained
        cd bin/x64/Release/net6.0-windows/win-x64/publish

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this release:
          - Describe your changes here

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Release-Artifacts
        path: src/DedicatedServerTool.Avalonia/bin/x64/Release/net6.0-windows/win-x64/publish/*
